### ISSUE TITLE
How to plot floating figures

### ISSUE THREAD

**Issue by ImmanuelSamuel** [arokem/python-matlab-bridge#101]
Hi, How can I run "figure" in a ipython cell and get the figure on a floating window? Right now I get a blank space inline. I would like to plot an image and use matlab figure properties. I also have some custom tools on an interactive figure window. Is this possible?
Thanks

**Comment by blink1073** [comment]
I think I traced the issue (at least on Linux).  Since we are always running the `matlabserver` function, the GUI event loop is not able to run.   You can test it with the following snippet:

```
function loop()
  plot([1,2,3])
  while 1
  end
end
```

If you run this function, the plot is not shown until you hit Ctrl+C.  If you remove the infinite while, the plot is shown after the function ends.

**Comment by blink1073** [comment]
But this works:

```python
plot([1,2,3])
  while 1
  end
end
```

**Comment by blink1073** [comment]
Hmm, the *actual* inner loop appears to be [here](https://github.com/arokem/python-matlab-bridge/blob/master/messenger/src/messenger.c#L36), which means we'd have to go to a non-blocking `zmq_read` to support a GUI event loop.
