### ISSUE TITLE
Better handling of MATLAB errors

### ISSUE THREAD

**Issue by jakirkham** [arokem/python-matlab-bridge#117]
When getting an error from MATLAB, I don't get much information about other than the message below. So, I'm left to hunt through my code for the offending error, cut it down into small enough pieces to figure out what is going on, or just revert to using MATLAB. It would be nice to get a little more information like a descriptive string from MATLAB about the error.

"There was an error running the code:
...
Are you sure Matlab is started?"

**Comment by isbadawi** [comment]
This should be a trivial fix, since we do capture the error message. At [this line](https://github.com/arokem/python-matlab-bridge/blob/d7ecda327618e0920cd4b5adc0fe2a169f9d724a/pymatbridge/matlab_magic.py#L214), we can catch the `MatlabInterperterError` (and fix the typo in the name :s) instead of having a bare `except`, and use the error message it gives. (You could still have a catch all `except` in case there are other issues.)

I'd implement this now but I'm about to head off to work. Feel free to send a PR and I'll merge it. Otherwise I can get to it later this evening.

**Comment by jakirkham** [comment]
Sorry for the rebasing noise. There is a simple fix. If you want to improve on it, feel free.
