### ISSUE TITLE
When a socket-connected matlab instance is already present mlab.start() creates another matlab instance but connects to the one already available

### ISSUE THREAD

**Issue by mmagnuski** [arokem/python-matlab-bridge#168]
This can be easily seen when one initiates a py-mat bridge, creating a socket-connected matlab instance (instance **A**) but then restarts python kernel and initiates the bridge again.
This creates another matlab instance (**B**), but when **B** is up and running it finds that python has already connected back to **A**. Not surprisingly **B** is not happy about it (python says "come play with me!" and then "sorry, I'm busy")  and complains.

It would be better if a new matlab instance was called only when a socket-connected one was not available.

**Comment by arokem** [comment]
Wouldn't this be resolved by using two different socket addresses? 

For example: 

```python
import pymatbridge as pymat
m1 = pymat.Matlab(socket_addr='ipc:///tmp/pymatbridge1')
m2 = pymat.Matlab(socket_addr='ipc:///tmp/pymatbridge2')
m1.start()
m2.start()
m1.run_code('a=1')
m2.run_code('whos')
m2.run_code('a=2')
m1.run_code('a')
```

**Comment by blink1073** [comment]
@mmagnuski, are you saying close and restart a python session, or open a second session while the first is still running?

**Comment by mmagnuski** [comment]
@blink1073:
I restart python session, or more precisely - restart ipython notebook kernel. I leave the matlab session spawned by pymatbridge open.
Opening a new matlab session is quite slow on my computer so I like the fact that I get connected quickly to the previous matlab session (previous = opened before restarting python kernel), but then spawning another matlab session is unnecessary if pymatbridge connected to the previous one.

@arokem: the thing is - I don't need two concurrent matlab sessions :)

**Comment by blink1073** [comment]
This would require us to keep track of opened Matlab sessions and attempt to reconnect with them after the fact.  IMO, that is beyond the scope of pymatbridge and the spawned Matlab session should close when the pymatbridge one does.  (This is what #169 does).

**Comment by neuromusic** [comment]
Unlike @mmagnuski I actually *do* need concurrent matlab sessions, as I'm running in a multi-user environment. We have a shared server where each user gets an iPython notebook server. I am trying to get the matlab_kernel running so that our Matlab users can also use the Jupyter environment. However, under the current configuration, every matlab_kernel launches pymatbridge with the default socket.

For my specific use-case I'd like for each matlab_kernel to get its own matlab instance. So maybe I need to focus my attention there.

But even for pymatbridge, it seems very weird to me to setup the default socket like this. For example it took me a while to realize that if I start two Matlab() instances and specify different executables...
``` python
import pymatbridge as pymat
m1 = pymat.Matlab('/usr/local/MATLAB/R2011a/bin/matlab')
m2 = pymat.Matlab('/usr/local/MATLAB/R2015a/bin/matlab')
m1.start()
m2.start()
```
both are communicating with the m1 instance. So even though I specified that I wanted `m2` to use R2015a
``` python
m2.run_code('ver')
```
Shows that I'm connected to R2011a

I ran into issues getting the master installed so I can't test what actually happens in a multi-user environment, but it seems at best very confusing, certainly problematic, and at worse a security risk (if UserB can connect and execute Matlab code on UserA's instance running with their permissions).

**Comment by arokem** [comment]
What would be a good solution? Would it make sense to assign a new random
socket to each instance? As I understand it, zmq sockets can just be an
arbitrary location on the file-system, so we can generate random temporary
file-names as sockets for each instance.

**Comment by neuromusic** [comment]
I'm by no means an IPC or ZMQ expert, but yes, that would make sense to me. `ipc:///tmp/pymatbridge/<uuid>` or something of the sort as the default socket

**Comment by neuromusic** [comment]
This of course doesn't prevent a malicious UserB from connecting to UserA's instance by specifying the their socket (I think?), but it would prevent accidental collisions.

**Comment by arokem** [comment]
Yes - I think that it would be very hard to do this securely, but these
problems might be (are?) better solved at the level of access control to
the environment (e.g the more general jupyter level).

**Comment by arokem** [comment]
How's this? #182

**Comment by neuromusic** [comment]
Looks like that should work. I'll give it a roll.

Looking more closely, it seems that ZMQ launches IPC sockets with 755 permissions under the user who launched it, so my security worries are probably moot (at least on Unix).

**Comment by blink1073** [comment]
Thanks for the kick in the pants, @neuromusic, user feedback is much appreciated.  :smile:

**Comment by neuromusic** [comment]
@blink1073 thanks for the rapid responses!

**Comment by neuromusic** [comment]
ok @arokem that works, but I'm going to cast a vote in favor of `"ipc:///tmp/pymatbridge-%s"%str(uuid4())` which makes it easier know that the sockets belong to pymatbridge. e.g. you can do `ls -l /tmp/pymatbridge-*` to get all of the open sockets

**Comment by arokem** [comment]
Good idea. Thanks for the input!

**Comment by neuromusic** [comment]
fantastic. between the quick responses of @arokem and @blink1073 our whole lab can run matlab_kernels on our lab's server. thanks all!!!

**Comment by arokem** [comment]
Out-of-scope for the complete solution, and resolved otherwise :-)
