### ISSUE TITLE
pip install getting old(?) version

### ISSUE THREAD

**Issue by bwilfley** [arokem/python-matlab-bridge#237]
Hi all,

(Please forgive my newbish question.)

I installed pymatbridge using pip3. When I look at the code publish.py, it appears that I'm getting a version before the fix for IPython.nbformat.

Should I be installing from the PyPI package?

Thanks

**Comment by arokem** [comment]
You are correct. It's been a while since we put out a release (May 2015). I
have been limited in terms of bandwidth to work on this, and I no longer
have access to Matlab(!). And Octave has not been too cooperative lately
either (see our automated testing...), so it's been challenging to maintain
this. Nevertheless, we should probably put out a release soon.

**Comment by arokem** [comment]
For the time being: best to install from the current `master` branch on
Github.

**Comment by bwilfley** [comment]
Thanks, Ariel. 

I found a reference to installing 'master' with pip:
>> pip3 install https://github.com/arokem/python-matlab-bridge/archive/master.tar.gz

Seems to have worked.
